spring:
  application:
    name: order-service

server:
  port: 60003

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, refresh, health, info
eureka:
  instance:
    instance-id: order-msa-instance

---
spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: dbUrl
    driver: com.h2.Driver
    username: local
    password: password1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

message:
  owner: 로컬 주문
  content: :) 로컬 주문 서비스 입니다. :)
jwt:
  token:
    key: local my_secret_key_change_version_change_bus_change

---
spring:
  profiles: dev
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: dbUrl
    driver: com.h2.Driver
    username: dev
    password: password1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
message:
  owner: dev 주문
  content: dev :) 주문 서비스 입니다. :)
jwt:
  token:
    key: dev my_secret_key_change_version_change_bus_change